# Generated by Django 4.0.4 on 2022-05-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0002_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookModel',
        ),
    ]
