# Generated by Django 4.0.4 on 2022-05-30 14:48

import app_lib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0003_rename_book_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=30)),
                ('isbn', models.CharField(max_length=30)),
                ('issuedate', models.DateField(auto_now=True)),
                ('expirydate', models.DateField(default=app_lib.models.get_expiry)),
            ],
        ),
    ]
