# Generated by Django 4.0.4 on 2022-05-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0004_issuedbook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssuedBook',
            new_name='IssueBook',
        ),
    ]
