# Generated by Django 4.0.4 on 2022-06-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lib', '0005_rename_issuedbook_issuebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueBook',
            new_name='IssuedBook',
        ),
    ]
